-- Full Schema Migration Script for AYJALE.COM (Final Version)
-- Run this in the Supabase SQL Editor of your FRESH project.

-- ==========================================
-- 1. Enable Essentials
-- ==========================================
create extension if not exists "uuid-ossp";

-- ==========================================
-- 2. Profiles Table (Users)
-- ==========================================
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    role TEXT CHECK (role IN ('candidate', 'company', 'admin')),
    name TEXT,
    title TEXT,
    bio TEXT,
    location TEXT,
    city TEXT, -- Added for compatibility
    phone TEXT,
    phone_number TEXT, -- Added for frontend compatibility
    skills TEXT,
    cv_url TEXT,
    photo_url TEXT,
    logo TEXT, -- Added alias for logo_url
    logo_url TEXT,
    website TEXT,
    linkedin TEXT,
    industry TEXT,
    company_size TEXT,
    founded_year TEXT,
    terms_accepted BOOLEAN DEFAULT FALSE,
    terms_accepted_at TIMESTAMP WITH TIME ZONE,
    rfc TEXT,
    address TEXT,
    recruiter_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. Jobs Table
-- ==========================================
CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    type TEXT, -- e.g., Full-time, Remote
    salary_min NUMERIC,
    salary_max NUMERIC,
    salary TEXT, -- Added for display compatibility
    salary_currency TEXT DEFAULT 'MXN',
    currency TEXT DEFAULT 'MXN', -- Added for frontend compatibility
    salary_period TEXT DEFAULT 'mensual',
    requirements TEXT,
    benefits TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    active BOOLEAN DEFAULT TRUE, -- Alias for code compatibility
    is_confidential BOOLEAN DEFAULT FALSE, -- Added for frontend compatibility
    category TEXT, -- Added for frontend compatibility
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '30 days'),
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. Applications Table
-- ==========================================
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE NOT NULL,
    candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'applied' CHECK (status IN ('applied', 'reviewing', 'interviewing', 'offer', 'hired', 'rejected')),
    resume_url TEXT,
    cover_letter TEXT,
    comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(job_id, candidate_id)
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. Messages Table (Chat)
-- ==========================================
CREATE TABLE public.messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    application_id BIGINT REFERENCES public.applications(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES public.profiles(id) NOT NULL,
    content TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 6. Contact Unlocks (Business Logic)
-- ==========================================
CREATE TABLE public.contact_unlocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(company_id, candidate_id)
);

ALTER TABLE public.contact_unlocks ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 7. Psychometric & Evaluation Tables
-- ==========================================

-- Psych Items
CREATE TABLE public.psych_items (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    trait TEXT NOT NULL,
    keyed TEXT DEFAULT 'plus',
    difficulty FLOAT DEFAULT 0.0,
    discrimination FLOAT DEFAULT 1.0,
    is_validity_check BOOLEAN DEFAULT FALSE,
    validity_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.psych_items ENABLE ROW LEVEL SECURITY;

-- Test Sessions
CREATE TABLE public.test_sessions (
    id SERIAL PRIMARY KEY,
    candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    end_time TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'in_progress',
    current_theta JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.test_sessions ENABLE ROW LEVEL SECURITY;

-- Item Responses
CREATE TABLE public.item_responses (
    id SERIAL PRIMARY KEY,
    session_id INTEGER REFERENCES public.test_sessions(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES public.psych_items(id),
    response_value INTEGER,
    response_time_ms INTEGER,
    mouse_trajectory_entropy FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.item_responses ENABLE ROW LEVEL SECURITY;

-- Candidate Profiles (Assessment Results)
CREATE TABLE public.candidate_profiles (
    id SERIAL PRIMARY KEY,
    candidate_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_id INTEGER REFERENCES public.test_sessions(id),
    scores JSONB NOT NULL,
    validity_flags JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.candidate_profiles ENABLE ROW LEVEL SECURITY;

-- Evaluation Tests Catalog
CREATE TABLE public.evaluation_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('psychometric', 'cognitive', 'language')),
    time_limit_minutes INTEGER,
    config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.evaluation_tests ENABLE ROW LEVEL SECURITY;

-- Seed Evaluation Data
INSERT INTO public.evaluation_tests (title, description, type, time_limit_minutes) VALUES 
('Perfil Conductual (Big 5)', 'Evaluación de rasgos de personalidad en el entorno laboral.', 'psychometric', 15);

-- Seed Psych Items
INSERT INTO public.psych_items (text, trait, keyed, difficulty, discrimination) VALUES
('Suelo tomar la iniciativa en situaciones grupales.', 'Extraversion', 'plus', -0.5, 1.2),
('Me siento cómodo siendo el centro de atención.', 'Extraversion', 'plus', 0.2, 1.5),
('Presto atención a los detalles más pequeños.', 'Conscientiousness', 'plus', -0.2, 1.0),
('Me estreso con facilidad ante cambios repentinos.', 'Neuroticism', 'plus', 0.5, 1.1),
('Tengo una imaginación muy viva.', 'Openness', 'plus', -0.1, 1.3),
('Me intereso por los problemas de los demás.', 'Agreeableness', 'plus', -0.8, 0.9);

-- ==========================================
-- 8. Functions & Triggers
-- ==========================================

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, name)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'role', 'candidate'),
    COALESCE(new.raw_user_meta_data->>'name', 'New User')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==========================================
-- 9. RLS Policies (Consolidated)
-- ==========================================

-- PROFILES
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true); 

-- JOBS
CREATE POLICY "Jobs are viewable by everyone" ON jobs FOR SELECT USING (true);
CREATE POLICY "Companies can insert own jobs" ON jobs FOR INSERT WITH CHECK (auth.uid() = company_id);
CREATE POLICY "Companies can update own jobs" ON jobs FOR UPDATE USING (auth.uid() = company_id);
CREATE POLICY "Companies can delete own jobs" ON jobs FOR DELETE USING (auth.uid() = company_id);

-- APPLICATIONS
CREATE POLICY "Candidates can create applications" ON applications FOR INSERT WITH CHECK (auth.uid() = candidate_id);
CREATE POLICY "Candidates can view own applications" ON applications FOR SELECT USING (auth.uid() = candidate_id);
CREATE POLICY "Companies can view applications for their jobs" ON applications FOR SELECT USING (
    EXISTS (SELECT 1 FROM jobs WHERE jobs.id = applications.job_id AND jobs.company_id = auth.uid())
);
CREATE POLICY "Companies can update applications for their jobs" ON applications FOR UPDATE USING (
    EXISTS (SELECT 1 FROM jobs WHERE jobs.id = applications.job_id AND jobs.company_id = auth.uid())
);

-- MESSAGES
CREATE POLICY "Users can view messages for their own applications" ON messages FOR SELECT USING (
    EXISTS (SELECT 1 FROM applications WHERE applications.id = messages.application_id AND applications.candidate_id = auth.uid())
);
CREATE POLICY "Companies can view messages for their job applications" ON messages FOR SELECT USING (
    EXISTS (SELECT 1 FROM applications JOIN jobs ON applications.job_id = jobs.id WHERE applications.id = messages.application_id AND jobs.company_id = auth.uid())
);
CREATE POLICY "Users can insert messages" ON messages FOR INSERT WITH CHECK (
    -- Candidate
    (EXISTS (SELECT 1 FROM applications WHERE applications.id = messages.application_id AND applications.candidate_id = auth.uid()))
    OR
    -- Company
    (EXISTS (SELECT 1 FROM applications JOIN jobs ON applications.job_id = jobs.id WHERE applications.id = messages.application_id AND jobs.company_id = auth.uid()))
);

-- CONTACT UNLOCKS
CREATE POLICY "Companies can view their own unlocks" ON contact_unlocks FOR SELECT USING (auth.uid() = company_id);
CREATE POLICY "Companies can create unlocks" ON contact_unlocks FOR INSERT WITH CHECK (auth.uid() = company_id);

-- PSYCHOMETRICS
CREATE POLICY "Everyone can read psych_items" ON public.psych_items FOR SELECT USING (true);
CREATE POLICY "Users can create own sessions" ON public.test_sessions FOR INSERT WITH CHECK (auth.uid() = candidate_id);
CREATE POLICY "Users can read own sessions" ON public.test_sessions FOR SELECT USING (auth.uid() = candidate_id);
CREATE POLICY "Users can update own sessions" ON public.test_sessions FOR UPDATE USING (auth.uid() = candidate_id);
CREATE POLICY "Users can read own responses" ON public.item_responses FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.test_sessions WHERE id = item_responses.session_id AND candidate_id = auth.uid())
);
CREATE POLICY "Users can insert own responses" ON public.item_responses FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.test_sessions WHERE id = item_responses.session_id AND candidate_id = auth.uid())
);
CREATE POLICY "Users can read own candidate profile" ON public.candidate_profiles FOR SELECT USING (auth.uid() = candidate_id);

-- EVALUATION TESTS
CREATE POLICY "Tests are viewable by everyone" ON evaluation_tests FOR SELECT USING (true);


-- ==========================================
-- 10. Storage Configuration
-- ==========================================
-- Tip: Remember to create 'avatars', 'cvs', and 'audio' buckets as PUBLIC in the Dashboard.
