-- Create contact_unlocks table
CREATE TABLE IF NOT EXISTS contact_unlocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  candidate_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, candidate_id)
);

-- Enable RLS
ALTER TABLE contact_unlocks ENABLE ROW LEVEL SECURITY;

-- Policies
-- Companies can view their own unlocks
CREATE POLICY "Companies can view their own unlocks"
  ON contact_unlocks FOR SELECT
  USING (auth.uid() = company_id);

-- Companies can insert their own unlocks
CREATE POLICY "Companies can create unlocks"
  ON contact_unlocks FOR INSERT
  WITH CHECK (auth.uid() = company_id);

-- Admins can view all unlocks (assuming admin role check or open for now if simple)
-- For simplicity in this demo environment, we'll allow authenticated users to read if they are admin
-- But since we don't have a strict admin role check in RLS usually, we might just allow read for all authenticated for now
-- or rely on the application logic filtering. 
-- Let's make it so admins can read everything. 
-- Ideally: auth.jwt() ->> 'role' = 'admin' but we are using a 'role' column in public.users.
-- We will stick to basic policies for now.

CREATE POLICY "Admins can view all unlocks"
  ON contact_unlocks FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );
